Update dev-depend-trigger-jenkin.yml

diff --git a/.github/workflows/dev-depend-trigger-jenkin.yml b/.github/workflows/dev-depend-trigger-jenkin.yml
--- a/.github/workflows/dev-depend-trigger-jenkin.yml
+++ b/.github/workflows/dev-depend-trigger-jenkin.yml
@@ -11,7 +11,7 @@ jobs:
       - name: Step 1
         run: |
           echo "Running Job 1"
-          exit 1  # This will cause the job to fail
+          # exit 1  # This will cause the job to fail
 
   job2:
     needs: job1
